env:
  global:
  - secure: PPkh+Z6+NR6jyNp2UJ7apRGYbvEKPbQOff+hvInls2lpVr8SsYEvjlTHvzbn4raHrGnPU8VXMDr7F0ze7T3Y7GPgq+n/xn+3SNnLyqbkqaAa4buKPIxBLsj6/ZKr7cZ+oiG8N1dO8beA/5KaVSSTXwnkI+smHn5P9jL3GYxui6E=
  - secure: VvHTiGLRlIj87cWPRR8LrAxxtBcBq+HRZ4b2+ZkXumcE/KiSB5pcO5fDRRQ+fJEPnAVCqmv9dJR/C5wSfrPKlbJ7qrCqss1yvNyEnXLxfF18bIA4VfcZj50tsJee7WsuFJt/XQRxqkDwju12jFqbQs5u3E45CGaSHdmTos6YPFE=
  - secure: ZRi+4MhdkHJz5C9LVkVk6E0atOBCZau95HQb59xKVVkttJ9elW3si0BYJnM9oU1KO8F+06Rex2grgUywPMAmxerpgfBL+CtGNuGLUXFA3R5FTC8jsGOyOLquwghtLRXFSuer3F0Q9dkfXLHLTzdiC8wJbFGC0sENmzWqu1ujrM0=
  - secure: Yb31EXfdjK/E1LubLKsc6/YCv3wvAyNyDnfHron1204ElPpGouOohV9ps43lWp90ftUet794AIMeeccndc6RDOj01utom4FzV6+C0Xek+0DWp/O7mo6MYPm0DnweZzkYABEw5cjrjbmgQuIdrhn+7GIYNvTdIGTllnOpZG5RrE4=
  - secure: GwPOqAqfzFtSLMCmdUkBuf5eFmg46XQnczoTyrCAa0HEliM3OD6pvs8nbqquEhSu+ZUYQcNZMYnivNdqNJoPVbHR4USppYOxzYZ1kEmM1TyMvNmHiu9TgqD9ymKAtlq8QoLsZbZdgJVyDDMoT82BsXx0dHM+hGd6V1w7geThPZU=
  - secure: IxyQ7Z7kfp4dGiM7+OiCcRiA8GvQdRnBIqC/2BvEb/D1p7R8KsDovjyaFtRE6d+GFKdA9llNaYtC1QUYcHajgB1YvTrnktR+dMAhApvBYZyzDFyi87vfroV0ST2LfDn6c0cTMruOOiMgorGkV902KLCDbYryX/ZdKOv3t20xh9w=
  - secure: LIemnpD7QEDdLwuvTiNShV1R3BCs48HbtLwttGWceHZ7NEUm8zDssEYHclQArhyDxPCuAxo8r6VgNz3BeyYvODmWbXdQHd5tarXuBRaHOMWhP2v0tqYRDlDRGRKhpklcBNEDdSd7gZ2yuQqI0MD1a2PepRgiQlq0Xc9RYbqWuLU=
  - secure: WH0Ac5OMwXRF47ecIXM7BAE0Q1aQ7g0eGL2wvNUStQml5CLt43cTWTROb5cegZTk0Vc7VELt0yJwSaW0vJq3nHwQbLMqNrOKkrs3aLJqfpnB81wE317sgEGk4zScnYBxdxLd7xA5n+ZH5Pza1fwa9ggdL5ltuQZs4KbQhU6ynGw=
  - secure: S40gOkuAOaqeAbsgGV/iX+5cFLUtBIrb7belNZW8pXNRUPM5cTLyqOf1rBjVRu4oYFp2JoEfkKUxRWp544Gknn3JwqTP26uHtWIcmQr0PLWzl5OtFSUVfY/dvIIx5ig6X7JcFpwiQEpnTjALXCU7YOXBZgeEv5YsomPl7Rx4bZA=
  - secure: bu83sR9jEsJCEtd1S6KhH2LU13TGXgrQ3vQxZYGctv07bunxagYRFKdaS+7JsJHJE0gYdCd35mol5sIkUfKBJeyqosFddCi5gcFUrJVp8K8Q4I7/oSyFK3RGoBH8HQvzHnGfK8u1y1M2d1DVVufBNXfi3XWztm11I1477pA412A=
  - secure: DHw6JG0HpSmbnh6z500BIMNQAPkVIRlbncyGTejHq1kF3/QaXLlw/6j4k7eYwApX/dm96kgca25VLi+WOF0eHElYSnj/zPjkQ+Ft72/3UpfnHOdpCOopBTLYG4J01SGU8SiBYhZqM8aXQYyBcu6Chq8DZBEBP7DV8TUiTvGNsxk=
  - secure: CsedWXmEJ0WfimAvSCqBzxwLR6/g8Z/cwYskvpTqwfAwMPg/D+mY++/LH9BCXbHtMRsntDrp9Wqoq7Brco6a8ajEt+TAL0bZSYghvhkVi5Iqjb4O2nUc+MntEcEzpQRvcNZAU6QxXi35ztOad/7524yrQrx51vojsq9QoXvfL48=
  - secure: cPkiBtoFyvu72zMIltAGGI/fsKuQzqnNdzSbOJ2ioJRqBLl0TjRpuZMDpY9g7kBg9hVfEzeYd5QKBD8W2FNUqdrwW9LkhXkpd7Xru0DPpSVrKVfz04U8gfLmI56pMLX8aUidsSDWP1odOP4L3pZq5LB74Wak5IWcydNUhzROPEQ=
  - secure: V/jVYs0v/HxaXMho5GRoaEq0bYUXajM9hiHAJqGmg56I/fltaqShiYJQlAm8NFT2W8HAomyJcvZgJI7edVdQoDf51yvJHfzZg1xWlIAWvJYKTYR8/A8S7uNsEi8OGbK/4oLaY3VrVhCSNSAnJ/d1aF7ylyzOTfqmDsFrJbghkHE=
  - secure: CGxPcw2Bzh+iPQeXQKjPeVnruupizvUlkLxG+GdgyjrNgFG0+QNcGjt5cpLnoBoBc0p7TjGbzkAwl4JnCVpGWMCsUUvK+T70bYzTTkvHBqmiCerwYtkFlCGCXtJlHWjjvvL4oM6/5ouJxVL0hQh5+ZLCTdaxGEoPItasepFNRIQ=
  - secure: KIspfc8YZvbDw1jdiuNTrpJuy484jnIumIkKFlx059xMqTWPBEHX6SXqQQYkIe5hStmvUIoV9RUGR+as6gA3PlFabGuyXV7Bu8Aoh5ceACY+u3//tl+I//gYwCv3svHmfiqp+TwWY3dZkZ7R41aEcF9SXHS24UUWC2wLtDbcl+w=
  - secure: EYfR8OnPJJcQpfX9Bk2R7Qq2/O2BzLSA+QInJTvJlTAiMY64aGHjsG9Mn3Vkh8JguIJCmsQ1Y6rul7qQ+NuTSXNy5f0xDdltiXJEHrOPDW8z9gLzWxp4v+oJoxfUXdPwckeEEZXv8O03G5gePHuEmPFkAH/0l3wjf7SGJh/c+U4=
  - secure: HmUZXmQg401zhPemnElcTlAokvaehAw8y+YfdSMC8LwBjc0dmuSY0z/PLzBDf+QbuWXhPuztS9IsHfHqB4w08N0/oZdBjhxtwrgrVsPTgwaRF/VOt5ho6H9dVeVI06TozEo6I8Ab+6EJTvaTsQVrlX+NiuGqMYTmaOYkORP7e50=
  - secure: aYP+s5/K7bZ6blSKh/8FKMY0FrjcJLQipUs3VEupg1dIW1+ZpDRV9zIP9bXF8Snb2n526H0kOr5OvL5Ism/xvPFa50sAdUev+OtdIzclfYHVWiiZRCcyhEuxVu2AG4u4UP/MPgAt9vhizwxwBCGxXg2bL8m3tCK8Z5D+cY8QyfE=
  - secure: QoeV6LLNitOPI8KYBe4nYU78lmarOwG3Mmen9j9fl8AZDzhjQHKqfd//0g4IhsRsEfeBjNnZMjk5H73QxCJG8Co5cRebK7mSpK5goF3UerjtcCV/sz6vZQZ3r5EcwGWgwaFxKN/TZoT2HiU2UqmbhhbEUlx7piSKIhQOVJe+fco=
  - secure: NghrgFFJP8RdO9Tcl8JiiG2AEz9Z3OQ7b5EuXfhRkrdCJyR/RzeoYkoiv49fRI7xHIs+C69bDK0ieHV4yYobp7IPxm+2eksWjh46wAPPpZ50Q+PhyvvRoJSNsIH16Ko7BoWyte4ezGNDH2zzf79rCFC286tuXN69eBXymV/JpbI=
  - secure: EVssah1UoVZjxYXUL3XGDYqkD8PxNL1YxDiz4bZKs4Ycsiz65kie66cqMFPyv3YflaePRhlFwUgIRUH1n5kpbV632fFKwLEPhrBPOWQCUW6s8x00eL3d/jSx/3snzbbtS/g/oFuPq+7FF3Pa2Dy3NZKFvHrHAxeKT1+rKFPGs4o=
  - secure: A61GV+H7aJ9HDGIlGYmDUl7lLQdSXHITs4QeM8CjVxAq3oqjQFGKGL+KzIDwVE8/FzXNHd3PMY4Ih2efsK2Bubp7Js9CRZXU9c9YxqWnya2pLrPKObiUOVBKCaSs9C7OAIGbPf7geQ/AYrN6sIGsSgPM53HnJFVrwaqWh8VvL80=
  - secure: DVd+tneP35+P4PYVk0VsudQavdirlt2EwMFOY2uE7APxSjKIEr+QNMCrxENm2K4JCZQeORrK5GzBBS4x1ZKJ6W7N1drRGhkUMu/qh1fT+7b/HAavtmezr+c+Pe/BF6Q+TCcIoIklLrqLH3jCbU8MdIsHfGlT0Q6eFNf0lULlkNs=
  - secure: MKVjs5siA4ThPOhk3ox2ZJPGTB9KOsgL0q6HTH111SpP6/J54G6mRATbRGRrE4IuAI9AI6NudUGwW3vv28IM+5NIUR8B9CdumfFvi7VWBmSLAcw5Z42Mwms5AMKP26HhlxXqGlvoUiNFZ8jtN9Fck/27HY4eCw6kgGpBiYM8pbQ=
  - secure: NPdJC5FrTH0vBNPH4JFCfP8UBateJJAKobQp+BCoF5PqRcDPVkTZbquZz7qN/b2Vx4tsJnWFTDFvGW7KeCibTPrX5R598hI9iLGLSwRToWrx4h+ZoJdHUjdrK9Eli8jKF4XfQ/0jVI/Ch5KtKJ5zVTCZVXO+AZ6XrExLsPjxMC4=
  - secure: EYPha3v+IgpChrOLZ5zwZsbNDlCm9RDzhqSp7FF1U6oRXOiSfX1jGB0FlgmXBF7IWtot+2VEBJ7UcL6eR0ieljSinL8+g/7Ab8plF/JveEQQYTZvjL6pMW2Cb70RzJAd+PqjVHoHVBRU/EsuTRxZPJqQP4yNzGLlAPCwrJVU/jM=
  - secure: MnSCljU2DqVp4Ot5kHzC56/vBrt7lRFSIP0w675puLYov4r9/m5oFWMHrbB0qAPdThuu+T4n2gMiSJttMlCxKph2LIParj8eGLHUocxT792Zb9XVZEtVImQ/Ti0xhj1iuYvXSTr8hRfe9OuA5Etk0dZS+nqQ1NH/vhPdMlTxpF8=
  - secure: ZLX5mjt5ehQYDE/ZDbK2ZVurri9mgHq/Ml8fByN2J/mrdPvXovJ7Zq2p35bcFzafNErpoOu6fxGv/wFL7Jxg7h9WInDKfP0DqH8fxIru42ZyikPGtrR+9JkqWonCOmOTbQMCfTCbQoYlhPXnWrEeq0Vj+PHci5DvFrSYxvnq7+A=
  - secure: Kzdepdk/xUebqq7Gbyhr5AhsOHqBO5t7j0JHQq04HpeB4NbzoHdU8P+b9h9Lh6s1tU6u/XjL6OCsS7E3AHDScIngRQNVsxZxf2lJpBcvXqJ2OEXLa3x7EYlsyiopGOHwCdjDZZpP33bjv8fAfl9UnqsOMCssLU8Pm/6NVWRHfro=
language: java
script: mvn clean install
jdk:
- openjdk7
- oraclejdk7
before_install:
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -n $KEY_CHUNK_{0..29} >> ~/.ssh/id_ec2.b64
- cat ~/.ssh/id_ec2.b64 | tr -d ' ' | base64 -d > ~/.ssh/id_ec2.pem
- chmod 600 ~/.ssh/id_ec2.pem
before_deploy: echo 'TRAVIS_TAG - [$TRAVIS_TAG] Start uploading generated build to s3 bucket...'
deploy:
  provider: s3
  access_key_id: AKIAIKJCZLI22AHHWDAQ
  secret_access_key:
    secure: FeGk18F4BKWjT1migtlST2H98931++ajL34Dhv4RDs0MEcjY4rt2Fn2IeOGfj+nZQgdSfOVhJam8gDVwu5oxKSjMdevKeFEgobNFv1lfphCFNn9bBgPzRzEg7NqYHyR7f3au7NbIbe7oBKsALmHkc3b0umNawxBygTXgR16CbUk=
  bucket: mybuilds
  acl: public_read_write
  on:
    repo: aslammncs/AslamWebApp
  skip_cleanup: true
  local_dir: build
after_deploy: ssh -v -i ~/.ssh/id_ec2.pem ubuntu@52.74.126.53 "cd ~/configure-server ; sudo git pull origin master ; sudo sh ~/configure-server/install.sh"
