language: java
script: mvn clean install
jdk:
- oraclejdk7
- openjdk7
- openjdk6
before_install:
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "$x00$x01$x02$x03$x04$x05$x06$x07$x08$x09$x10$x11$x12$x13$x14$x15$x16$x17$x18$x19$x20$x21$x22" > ~/.ssh/id_rsa.b64
- cat ~/.ssh/id_rsa.b64 | openssl base64 -d > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
before_deploy: echo 'Start uploading my build to s3 bucket...'
deploy:
  provider: s3
  access_key_id: AKIAIKJCZLI22AHHWDAQ
  secret_access_key:
    secure: FeGk18F4BKWjT1migtlST2H98931++ajL34Dhv4RDs0MEcjY4rt2Fn2IeOGfj+nZQgdSfOVhJam8gDVwu5oxKSjMdevKeFEgobNFv1lfphCFNn9bBgPzRzEg7NqYHyR7f3au7NbIbe7oBKsALmHkc3b0umNawxBygTXgR16CbUk=
  bucket: mybuilds
  acl: public_read_write
  on:
    repo: aslammncs/AslamWebApp
  skip_cleanup: true
  local_dir: build
after_deploy: ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@52.74.126.53 "sudo sh ~/configure-server/install.sh"
