language: java
script: mvn clean install
jdk:
- oraclejdk7
- openjdk7
- openjdk6
before_install:
- openssl aes-256-cbc -K $encrypted_32fe5a4e37a3_key -iv $encrypted_32fe5a4e37a3_iv
  -in madpk-dep.pem.enc -out madpk-dep.pem -d
before_deploy: echo 'Start uploading my build to s3 bucket...'
deploy:
  provider: s3
  access_key_id: AKIAIKJCZLI22AHHWDAQ
  secret_access_key:
    secure: FeGk18F4BKWjT1migtlST2H98931++ajL34Dhv4RDs0MEcjY4rt2Fn2IeOGfj+nZQgdSfOVhJam8gDVwu5oxKSjMdevKeFEgobNFv1lfphCFNn9bBgPzRzEg7NqYHyR7f3au7NbIbe7oBKsALmHkc3b0umNawxBygTXgR16CbUk=
  bucket: mybuilds
  acl: public_read_write
  on:
    repo: aslammncs/AslamWebApp
  skip_cleanup: true
  local_dir: build
after_deploy: ssh -o StrictHostKeyChecking=no ubuntu@52.74.126.53 "sudo sh ~/configure-server/install.sh"
