language: java
script: mvn clean install
jdk:
- oraclejdk7
- openjdk7
- openjdk6
before_deploy:
 cp /home/travis/build/aslammncs/AslamWebApp/target/AslamWebApp.war /home/travis/build/aslammncs/AslamWebApp/build 
 "echo 'Start uploading my build to s3 bucket...'"
deploy:
  provider: s3
  access_key_id: AKIAIKJCZLI22AHHWDAQ
  secret_access_key:
    secure: FeGk18F4BKWjT1migtlST2H98931++ajL34Dhv4RDs0MEcjY4rt2Fn2IeOGfj+nZQgdSfOVhJam8gDVwu5oxKSjMdevKeFEgobNFv1lfphCFNn9bBgPzRzEg7NqYHyR7f3au7NbIbe7oBKsALmHkc3b0umNawxBygTXgR16CbUk=
  bucket: mybuilds
  acl: public_read_write
  on:
    repo: aslammncs/AslamWebApp
  skip_cleanup: true
  local_dir: build
after_deploy: "echo 'Upload done!'"
