language: java
script: mvn clean install
jdk:
- oraclejdk7
- openjdk7
- openjdk6

after_success:
- cd $HOME/$BUILD_HOME/AslamWebApp/target/
- cp AslamWebApp.war $HOME/$BUILD_HOME/AslamWebApp/build/
- cd $HOME/$BUILD_HOME/AslamWebApp/build
- scp -r $HOME/$BUILD_HOME/AslamWebApp/build/AslamWebApp.war ubuntu@ec2-52-74-74-62.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/



#before_deploy: "echo 'Start deploying the build to server...'"
#deploy: ./deploy.sh 
#after_deploy: "echo 'Upload done!'"
